api = "0.8"

[buildpack]
  description = "A buildpack for installing the approriate version of ICU (International Components for Unicode)"
  homepage = "https://github.com/paketo-buildpacks/icu"
  id = "paketo-buildpacks/icu"
  keywords = ["dotnet", "ICU", "unicode"]
  name = "Paketo Buildpack for ICU"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/icu/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:ef9d6f146acb4ec2eb32ed3e8f450cc49dcbdbc0ab4ff25f35ab6c55c1b0b0cd"
    cpe = "cpe:2.3:a:icu-project:international_components_for_unicode:78.3:*:*:*:*:c\\/c\\+\\+:*:*"
    id = "icu"
    licenses = ["BSD-2-Clause", "BSD-3-Clause", "ICU", "Unicode-TOU"]
    name = "ICU"
    os = "linux"
    purl = "pkg:generic/icu@78.3?checksum=04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245&download_url=https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source = "https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source-checksum = "sha512:04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/icu/icu_78.3_linux_amd64_jammy_ef9d6f14.tgz"
    version = "78.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:2a330de2f7094b4850e608a66d1038764d3cf5851cb03acd8b922b526fc3245b"
    cpe = "cpe:2.3:a:icu-project:international_components_for_unicode:78.3:*:*:*:*:c\\/c\\+\\+:*:*"
    id = "icu"
    licenses = ["BSD-2-Clause", "BSD-3-Clause", "ICU", "Unicode-TOU"]
    name = "ICU"
    os = "linux"
    purl = "pkg:generic/icu@78.3?checksum=04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245&download_url=https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source = "https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source-checksum = "sha512:04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245"
    stacks = ["io.buildpacks.stacks.jammy"]
    uri = "https://artifacts.paketo.io/icu/icu_78.3_linux_arm64_jammy_2a330de2.tgz"
    version = "78.3"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:69c8befaca7779f5b4f58d8b0304cd387215d8322a33f0c7b4ac61ccc6cd7e56"
    cpe = "cpe:2.3:a:icu-project:international_components_for_unicode:78.3:*:*:*:*:c\\/c\\+\\+:*:*"
    id = "icu"
    licenses = ["BSD-2-Clause", "BSD-3-Clause", "ICU", "Unicode-TOU"]
    name = "ICU"
    os = "linux"
    purl = "pkg:generic/icu@78.3?checksum=04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245&download_url=https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source = "https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source-checksum = "sha512:04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/icu/icu_78.3_linux_amd64_noble_69c8befa.tgz"
    version = "78.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:2934ea2e0d9bb59487aa6383005eae315db7c1d2910813511607f69d8e9770c8"
    cpe = "cpe:2.3:a:icu-project:international_components_for_unicode:78.3:*:*:*:*:c\\/c\\+\\+:*:*"
    id = "icu"
    licenses = ["BSD-2-Clause", "BSD-3-Clause", "ICU", "Unicode-TOU"]
    name = "ICU"
    os = "linux"
    purl = "pkg:generic/icu@78.3?checksum=04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245&download_url=https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source = "https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source-checksum = "sha512:04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245"
    stacks = ["io.buildpacks.stacks.noble"]
    uri = "https://artifacts.paketo.io/icu/icu_78.3_linux_arm64_noble_2934ea2e.tgz"
    version = "78.3"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:6a2dd92e4baf979f0fe6e7b8f13e2a76055a7d0a2cbf49c7adafb79b8e5f31db"
    cpe = "cpe:2.3:a:icu-project:international_components_for_unicode:78.3:*:*:*:*:c\\/c\\+\\+:*:*"
    id = "icu"
    licenses = ["BSD-2-Clause", "BSD-3-Clause", "ICU", "Unicode-TOU"]
    name = "ICU"
    os = "linux"
    purl = "pkg:generic/icu@78.3?checksum=04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245&download_url=https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source = "https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source-checksum = "sha512:04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245"
    stacks = ["io.buildpacks.stacks.resolute"]
    uri = "https://artifacts.paketo.io/icu/icu_78.3_linux_amd64_resolute_6a2dd92e.tgz"
    version = "78.3"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:90ec60430ab69b6860cad02de260dd0d879da25ce18010cd20756a0bdf03648b"
    cpe = "cpe:2.3:a:icu-project:international_components_for_unicode:78.3:*:*:*:*:c\\/c\\+\\+:*:*"
    id = "icu"
    licenses = ["BSD-2-Clause", "BSD-3-Clause", "ICU", "Unicode-TOU"]
    name = "ICU"
    os = "linux"
    purl = "pkg:generic/icu@78.3?checksum=04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245&download_url=https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source = "https://github.com/unicode-org/icu/releases/download/release-78.3/icu4c-78.3-sources.tgz"
    source-checksum = "sha512:04a49455e1489030c520a4bfd2664fa2171e7938d08f2acdbbcb1fda976639fd8b1f0704f2eec89ba59a7b6d118ceaab6ec5a096e40d9085a0895d91ce225245"
    stacks = ["io.buildpacks.stacks.resolute"]
    uri = "https://artifacts.paketo.io/icu/icu_78.3_linux_arm64_resolute_90ec6043.tgz"
    version = "78.3"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "icu"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[stacks]]
  id = "io.buildpacks.stacks.resolute"

[[targets]]
  arch = "amd64"
  os = "linux"

  [[targets.distros]]
  name = "Ubuntu"
  version = "22.04"

  [[targets.distros]]
  name = "Ubuntu"
  version = "24.04"

  [[targets.distros]]
  name = "Ubuntu"
  version = "26.04"

[[targets]]
  arch = "arm64"
  os = "linux"

  [[targets.distros]]
  name = "Ubuntu"
  version = "22.04"

  [[targets.distros]]
  name = "Ubuntu"
  version = "24.04"

  [[targets.distros]]
  name = "Ubuntu"
  version = "26.04"